
print (" you equation is ay=mx+c ")
a = float(input ("enter a:"))
m = float(input ("enter m:"))
c = float(input("enter c:"))
slope = float (m/a)
print("slope line", slope)
yin = float(c/a)
xin = float(-c/m)
print("yintercept:",yin)
print("xintercept:", xin)
